In [32]:
from tensorflow.keras.preprocessing.text import one_hot

In [33]:
sent = [
    "the glass of milk",
    "the glass of juice",
    "the cup of tea",
    "I am a good boy",
    "I am a good developer",
    "understand the meaning of words",
    "your videos are good"
]


In [34]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [35]:
# define vocabulary size
vocab_size = 10000

In [36]:
# one hot representation
one_hot_representations = [one_hot(words, vocab_size) for words in sent]
one_hot_representations


[[5291, 3889, 4476, 5458],
 [5291, 3889, 4476, 6134],
 [5291, 5960, 4476, 6757],
 [3900, 2548, 8525, 5787, 1767],
 [3900, 2548, 8525, 5787, 1165],
 [6399, 5291, 2387, 4476, 7788],
 [483, 4402, 8997, 5787]]

In [37]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [38]:
import numpy as np


In [39]:
# padding is use to make all the sentences of same length
sent_length = 8
embedded_docs = pad_sequences(one_hot_representations,padding ='pre',maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 5291, 3889, 4476, 5458],
       [   0,    0,    0,    0, 5291, 3889, 4476, 6134],
       [   0,    0,    0,    0, 5291, 5960, 4476, 6757],
       [   0,    0,    0, 3900, 2548, 8525, 5787, 1767],
       [   0,    0,    0, 3900, 2548, 8525, 5787, 1165],
       [   0,    0,    0, 6399, 5291, 2387, 4476, 7788],
       [   0,    0,    0,    0,  483, 4402, 8997, 5787]], dtype=int32)

In [40]:
# feature representation using embedding
dim=10
model = Sequential()
model.add(Embedding(vocab_size,dim,input_length  = sent_length))
model.compile('adam','mse')

c:\tf\tfenv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [41]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [42]:
embedded_docs[0]

array([   0,    0,    0,    0, 5291, 3889, 4476, 5458], dtype=int32)

In [43]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step


array([[[-4.89679463e-02,  1.08332261e-02, -2.36951597e-02,
          2.58294232e-02, -4.70095389e-02,  3.36948521e-02,
          1.72242783e-02,  1.29814260e-02, -2.90747415e-02,
          1.70796774e-02],
        [-4.89679463e-02,  1.08332261e-02, -2.36951597e-02,
          2.58294232e-02, -4.70095389e-02,  3.36948521e-02,
          1.72242783e-02,  1.29814260e-02, -2.90747415e-02,
          1.70796774e-02],
        [-4.89679463e-02,  1.08332261e-02, -2.36951597e-02,
          2.58294232e-02, -4.70095389e-02,  3.36948521e-02,
          1.72242783e-02,  1.29814260e-02, -2.90747415e-02,
          1.70796774e-02],
        [-4.89679463e-02,  1.08332261e-02, -2.36951597e-02,
          2.58294232e-02, -4.70095389e-02,  3.36948521e-02,
          1.72242783e-02,  1.29814260e-02, -2.90747415e-02,
          1.70796774e-02],
        [-1.49602294e-02,  1.48382299e-02, -4.54608798e-02,
         -1.84021965e-02,  1.47589296e-03,  9.88178328e-03,
         -2.74665654e-05,  1.36703365e-02, -2.555320